#define TEST_abs 0
#define TEST_acos 0
#define TEST_acos_example 0
#define TEST_acosh 0
#define TEST_acosh_example 0
#define TEST_add 1
#define TEST_add_bcast 1
#define TEST_and2d 0
#define TEST_and3d 0
#define TEST_and4d 0
#define TEST_and_bcast3v1d 0
#define TEST_and_bcast3v2d 0
#define TEST_and_bcast4v2d 0
#define TEST_and_bcast4v3d 0
#define TEST_and_bcast4v4d 0
#define TEST_argmax_default_axis_example 0
#define TEST_argmax_default_axis_example_select_last_index 0
#define TEST_argmax_default_axis_random 0
#define TEST_argmax_default_axis_random_select_last_index 0
#define TEST_argmax_keepdims_example 0
#define TEST_argmax_keepdims_example_select_last_index 0
#define TEST_argmax_keepdims_random 0
#define TEST_argmax_keepdims_random_select_last_index 0
#define TEST_argmax_negative_axis_keepdims_example 0
#define TEST_argmax_negative_axis_keepdims_example_select_last_index 0
#define TEST_argmax_negative_axis_keepdims_random 0
#define TEST_argmax_negative_axis_keepdims_random_select_last_index 0
#define TEST_argmax_no_keepdims_example 0
#define TEST_argmax_no_keepdims_example_select_last_index 0
#define TEST_argmax_no_keepdims_random 0
#define TEST_argmax_no_keepdims_random_select_last_index 0
#define TEST_argmin_default_axis_example 0
#define TEST_argmin_default_axis_example_select_last_index 0
#define TEST_argmin_default_axis_random 0
#define TEST_argmin_default_axis_random_select_last_index 0
#define TEST_argmin_keepdims_example 0
#define TEST_argmin_keepdims_example_select_last_index 0
#define TEST_argmin_keepdims_random 0
#define TEST_argmin_keepdims_random_select_last_index 0
#define TEST_argmin_negative_axis_keepdims_example 0
#define TEST_argmin_negative_axis_keepdims_example_select_last_index 0
#define TEST_argmin_negative_axis_keepdims_random 0
#define TEST_argmin_negative_axis_keepdims_random_select_last_index 0
#define TEST_argmin_no_keepdims_example 0
#define TEST_argmin_no_keepdims_example_select_last_index 0
#define TEST_argmin_no_keepdims_random 0
#define TEST_argmin_no_keepdims_random_select_last_index 0
#define TEST_asin 0
#define TEST_asin_example 0
#define TEST_asinh 0
#define TEST_asinh_example 0
#define TEST_atan 0
#define TEST_atan_example 0
#define TEST_atanh 0
#define TEST_atanh_example 0
#define TEST_averagepool_1d_default 0
#define TEST_averagepool_2d_ceil 0
#define TEST_averagepool_2d_default 0
#define TEST_averagepool_2d_pads 0
#define TEST_averagepool_2d_pads_count_include_pad 0
#define TEST_averagepool_2d_precomputed_pads 0
#define TEST_averagepool_2d_precomputed_pads_count_include_pad 0
#define TEST_averagepool_2d_precomputed_same_upper 0
#define TEST_averagepool_2d_precomputed_strides 0
#define TEST_averagepool_2d_same_lower 0
#define TEST_averagepool_2d_same_upper 0
#define TEST_averagepool_2d_strides 0
#define TEST_averagepool_3d_default 0
#define TEST_basic_conv_with_padding 0
#define TEST_basic_conv_without_padding 0
#define TEST_basic_convinteger 0
#define TEST_batchnorm_epsilon 1
#define TEST_batchnorm_example 1
#define TEST_bitshift_left_uint16 0
#define TEST_bitshift_left_uint32 0
#define TEST_bitshift_left_uint64 0
#define TEST_bitshift_left_uint8 0
#define TEST_bitshift_right_uint16 0
#define TEST_bitshift_right_uint32 0
#define TEST_bitshift_right_uint64 0
#define TEST_bitshift_right_uint8 0
#define TEST_cast_DOUBLE_to_FLOAT 0
#define TEST_cast_DOUBLE_to_FLOAT16 0
#define TEST_cast_FLOAT16_to_DOUBLE 0
#define TEST_cast_FLOAT16_to_FLOAT 0
#define TEST_cast_FLOAT_to_DOUBLE 0
#define TEST_cast_FLOAT_to_FLOAT16 0
#define TEST_cast_FLOAT_to_STRING 0
#define TEST_cast_STRING_to_FLOAT 0
#define TEST_ceil 0
#define TEST_ceil_example 0
#define TEST_clip 0
#define TEST_clip_default_inbounds 0
#define TEST_clip_default_max 0
#define TEST_clip_default_min 0
#define TEST_clip_example 0
#define TEST_clip_inbounds 0
#define TEST_clip_outbounds 0
#define TEST_clip_splitbounds 0
#define TEST_compress_0 0
#define TEST_compress_1 0
#define TEST_compress_default_axis 0
#define TEST_compress_negative_axis 0
#define TEST_concat_1d_axis_0 0
#define TEST_concat_1d_axis_negative_1 0
#define TEST_concat_2d_axis_0 0
#define TEST_concat_2d_axis_1 0
#define TEST_concat_2d_axis_negative_1 0
#define TEST_concat_2d_axis_negative_2 0
#define TEST_concat_3d_axis_0 0
#define TEST_concat_3d_axis_1 0
#define TEST_concat_3d_axis_2 0
#define TEST_concat_3d_axis_negative_1 0
#define TEST_concat_3d_axis_negative_2 0
#define TEST_concat_3d_axis_negative_3 0
#define TEST_constant 0
#define TEST_constant_pad 0
#define TEST_constantofshape_float_ones 0
#define TEST_constantofshape_int_zeros 0
#define TEST_conv_with_strides_and_asymmetric_padding 0
#define TEST_conv_with_strides_no_padding 1
#define TEST_conv_with_strides_padding 0
#define TEST_convinteger_with_padding 0
#define TEST_convtranspose 0
#define TEST_convtranspose_1d 0
#define TEST_convtranspose_3d 0
#define TEST_convtranspose_dilations 0
#define TEST_convtranspose_kernel_shape 0
#define TEST_convtranspose_output_shape 0
#define TEST_convtranspose_pad 0
#define TEST_convtranspose_pads 0
#define TEST_convtranspose_with_kernel 0
#define TEST_cos 0
#define TEST_cos_example 0
#define TEST_cosh 0
#define TEST_cosh_example 0
#define TEST_cumsum_1d 0
#define TEST_cumsum_1d_exclusive 0
#define TEST_cumsum_1d_reverse 0
#define TEST_cumsum_1d_reverse_exclusive 0
#define TEST_cumsum_2d_axis_0 0
#define TEST_cumsum_2d_axis_1 0
#define TEST_cumsum_2d_negative_axis 0
#define TEST_depthtospace_crd_mode 0
#define TEST_depthtospace_crd_mode_example 0
#define TEST_depthtospace_dcr_mode 0
#define TEST_depthtospace_example 0
#define TEST_dequantizelinear 0
#define TEST_det_2d 0
#define TEST_det_nd 0
#define TEST_div 0
#define TEST_div_bcast 0
#define TEST_div_example 0
#define TEST_dropout_default 0
#define TEST_dropout_random 0
#define TEST_dynamicquantizelinear 0
#define TEST_dynamicquantizelinear_expanded 0
#define TEST_dynamicquantizelinear_max_adjusted 0
#define TEST_dynamicquantizelinear_max_adjusted_expanded 0
#define TEST_dynamicquantizelinear_min_adjusted 0
#define TEST_dynamicquantizelinear_min_adjusted_expanded 0
#define TEST_edge_pad 0
#define TEST_elu 0
#define TEST_elu_default 0
#define TEST_elu_example 0
#define TEST_equal 0
#define TEST_equal_bcast 0
#define TEST_erf 0
#define TEST_exp 0
#define TEST_exp_example 0
#define TEST_expand_dim_changed 0
#define TEST_expand_dim_unchanged 0
#define TEST_eyelike_populate_off_main_diagonal 0
#define TEST_eyelike_with_dtype 0
#define TEST_eyelike_without_dtype 0
#define TEST_flatten_axis0 0
#define TEST_flatten_axis1 0
#define TEST_flatten_axis2 0
#define TEST_flatten_axis3 0
#define TEST_flatten_default_axis 0
#define TEST_flatten_negative_axis1 0
#define TEST_flatten_negative_axis2 0
#define TEST_flatten_negative_axis3 0
#define TEST_flatten_negative_axis4 0
#define TEST_floor 0
#define TEST_floor_example 0
#define TEST_gather_0 0
#define TEST_gather_1 0
#define TEST_gather_elements_0 0
#define TEST_gather_elements_1 0
#define TEST_gather_elements_negative_indices 0
#define TEST_gather_negative_indices 0
#define TEST_gathernd_example_float32 0
#define TEST_gathernd_example_int32 0
#define TEST_gemm_all_attributes 0
#define TEST_gemm_alpha 0
#define TEST_gemm_beta 0
#define TEST_gemm_default_matrix_bias 0
#define TEST_gemm_default_no_bias 0
#define TEST_gemm_default_scalar_bias 0
#define TEST_gemm_default_single_elem_vector_bias 0
#define TEST_gemm_default_vector_bias 0
#define TEST_gemm_default_zero_bias 0
#define TEST_gemm_transposeA 0
#define TEST_gemm_transposeB 0
#define TEST_globalaveragepool 0
#define TEST_globalaveragepool_precomputed 0
#define TEST_globalmaxpool 0
#define TEST_globalmaxpool_precomputed 0
#define TEST_greater 0
#define TEST_greater_bcast 0
#define TEST_gru_defaults 0
#define TEST_gru_seq_length 0
#define TEST_gru_with_initial_bias 0
#define TEST_hardmax_axis_0 0
#define TEST_hardmax_axis_1 0
#define TEST_hardmax_axis_2 0
#define TEST_hardmax_default_axis 0
#define TEST_hardmax_example 0
#define TEST_hardmax_negative_axis 0
#define TEST_hardmax_one_hot 0
#define TEST_hardsigmoid 0
#define TEST_hardsigmoid_default 0
#define TEST_hardsigmoid_example 0
#define TEST_identity 0
#define TEST_instancenorm_epsilon 0
#define TEST_instancenorm_example 0
#define TEST_isinf 0
#define TEST_isinf_negative 0
#define TEST_isinf_positive 0
#define TEST_isnan 0
#define TEST_leakyrelu 1
#define TEST_leakyrelu_default 1
#define TEST_leakyrelu_example 1
#define TEST_less 0
#define TEST_less_bcast 0
#define TEST_log 0
#define TEST_log_example 0
#define TEST_logsoftmax_axis_0 0
#define TEST_logsoftmax_axis_1 0
#define TEST_logsoftmax_axis_2 0
#define TEST_logsoftmax_default_axis 0
#define TEST_logsoftmax_example_1 0
#define TEST_logsoftmax_large_number 0
#define TEST_logsoftmax_negative_axis 0
#define TEST_lrn 0
#define TEST_lrn_default 0
#define TEST_lstm_defaults 0
#define TEST_lstm_with_initial_bias 0
#define TEST_lstm_with_peepholes 0
#define TEST_matmul_2d 1
#define TEST_matmul_3d 0
#define TEST_matmul_4d 0
#define TEST_matmulinteger 0
#define TEST_max_example 0
#define TEST_max_one_input 0
#define TEST_max_two_inputs 0
#define TEST_maxpool_1d_default 0
#define TEST_maxpool_2d_ceil 0
#define TEST_maxpool_2d_default 1
#define TEST_maxpool_2d_dilations 0
#define TEST_maxpool_2d_pads 1
#define TEST_maxpool_2d_precomputed_pads 1
#define TEST_maxpool_2d_precomputed_same_upper 1
#define TEST_maxpool_2d_precomputed_strides 1
#define TEST_maxpool_2d_same_lower 1
#define TEST_maxpool_2d_same_upper 1
#define TEST_maxpool_2d_strides 1
#define TEST_maxpool_3d_default 0
#define TEST_maxpool_with_argmax_2d_precomputed_pads 0
#define TEST_maxpool_with_argmax_2d_precomputed_strides 0
#define TEST_maxunpool_export_with_output_shape 0
#define TEST_maxunpool_export_without_output_shape 0
#define TEST_mean_example 0
#define TEST_mean_one_input 0
#define TEST_mean_two_inputs 0
#define TEST_min_example 0
#define TEST_min_one_input 0
#define TEST_min_two_inputs 0
#define TEST_mod_broadcast 0
#define TEST_mod_int64_fmod 0
#define TEST_mod_mixed_sign_float16 0
#define TEST_mod_mixed_sign_float32 0
#define TEST_mod_mixed_sign_float64 0
#define TEST_mod_mixed_sign_int16 0
#define TEST_mod_mixed_sign_int32 0
#define TEST_mod_mixed_sign_int64 0
#define TEST_mod_mixed_sign_int8 0
#define TEST_mod_uint16 0
#define TEST_mod_uint32 0
#define TEST_mod_uint64 0
#define TEST_mod_uint8 0
#define TEST_mul 0
#define TEST_mul_bcast 0
#define TEST_mul_example 0
#define TEST_mvn 0
#define TEST_mvn_expanded 0
#define TEST_neg 0
#define TEST_neg_example 0
#define TEST_nonmaxsuppression_center_point_box_format 0
#define TEST_nonmaxsuppression_flipped_coordinates 0
#define TEST_nonmaxsuppression_identical_boxes 0
#define TEST_nonmaxsuppression_limit_output_size 0
#define TEST_nonmaxsuppression_single_box 0
#define TEST_nonmaxsuppression_suppress_by_IOU 0
#define TEST_nonmaxsuppression_suppress_by_IOU_and_scores 0
#define TEST_nonmaxsuppression_two_batches 0
#define TEST_nonmaxsuppression_two_classes 0
#define TEST_nonzero_example 0
#define TEST_not_2d 0
#define TEST_not_3d 0
#define TEST_not_4d 0
#define TEST_onehot_negative_indices 0
#define TEST_onehot_with_axis 0
#define TEST_onehot_with_negative_axis 0
#define TEST_onehot_without_axis 0
#define TEST_or2d 0
#define TEST_or3d 0
#define TEST_or4d 0
#define TEST_or_bcast3v1d 0
#define TEST_or_bcast3v2d 0
#define TEST_or_bcast4v2d 0
#define TEST_or_bcast4v3d 0
#define TEST_or_bcast4v4d 0
#define TEST_pow 0
#define TEST_pow_bcast_array 0
#define TEST_pow_bcast_scalar 0
#define TEST_pow_example 0
#define TEST_prelu_broadcast 0
#define TEST_prelu_example 0
#define TEST_qlinearconv 0
#define TEST_qlinearmatmul_2D 0
#define TEST_qlinearmatmul_3D 0
#define TEST_quantizelinear 0
#define TEST_range_float_type_positive_delta 0
#define TEST_range_float_type_positive_delta_expanded 0
#define TEST_range_int32_type_negative_delta 0
#define TEST_range_int32_type_negative_delta_expanded 0
#define TEST_reciprocal 0
#define TEST_reciprocal_example 0
#define TEST_reduce_l1_default_axes_keepdims_example 0
#define TEST_reduce_l1_default_axes_keepdims_random 0
#define TEST_reduce_l1_do_not_keepdims_example 0
#define TEST_reduce_l1_do_not_keepdims_random 0
#define TEST_reduce_l1_keep_dims_example 0
#define TEST_reduce_l1_keep_dims_random 0
#define TEST_reduce_l1_negative_axes_keep_dims_example 0
#define TEST_reduce_l1_negative_axes_keep_dims_random 0
#define TEST_reduce_l2_default_axes_keepdims_example 0
#define TEST_reduce_l2_default_axes_keepdims_random 0
#define TEST_reduce_l2_do_not_keepdims_example 0
#define TEST_reduce_l2_do_not_keepdims_random 0
#define TEST_reduce_l2_keep_dims_example 0
#define TEST_reduce_l2_keep_dims_random 0
#define TEST_reduce_l2_negative_axes_keep_dims_example 0
#define TEST_reduce_l2_negative_axes_keep_dims_random 0
#define TEST_reduce_log_sum 0
#define TEST_reduce_log_sum_asc_axes 0
#define TEST_reduce_log_sum_default 0
#define TEST_reduce_log_sum_desc_axes 0
#define TEST_reduce_log_sum_exp_default_axes_keepdims_example 0
#define TEST_reduce_log_sum_exp_default_axes_keepdims_random 0
#define TEST_reduce_log_sum_exp_do_not_keepdims_example 0
#define TEST_reduce_log_sum_exp_do_not_keepdims_random 0
#define TEST_reduce_log_sum_exp_keepdims_example 0
#define TEST_reduce_log_sum_exp_keepdims_random 0
#define TEST_reduce_log_sum_exp_negative_axes_keepdims_example 0
#define TEST_reduce_log_sum_exp_negative_axes_keepdims_random 0
#define TEST_reduce_log_sum_negative_axes 0
#define TEST_reduce_max_default_axes_keepdim_example 0
#define TEST_reduce_max_default_axes_keepdims_random 0
#define TEST_reduce_max_do_not_keepdims_example 0
#define TEST_reduce_max_do_not_keepdims_random 0
#define TEST_reduce_max_keepdims_example 0
#define TEST_reduce_max_keepdims_random 0
#define TEST_reduce_max_negative_axes_keepdims_example 0
#define TEST_reduce_max_negative_axes_keepdims_random 0
#define TEST_reduce_mean_default_axes_keepdims_example 0
#define TEST_reduce_mean_default_axes_keepdims_random 0
#define TEST_reduce_mean_do_not_keepdims_example 0
#define TEST_reduce_mean_do_not_keepdims_random 0
#define TEST_reduce_mean_keepdims_example 0
#define TEST_reduce_mean_keepdims_random 0
#define TEST_reduce_mean_negative_axes_keepdims_example 0
#define TEST_reduce_mean_negative_axes_keepdims_random 0
#define TEST_reduce_min_default_axes_keepdims_example 0
#define TEST_reduce_min_default_axes_keepdims_random 0
#define TEST_reduce_min_do_not_keepdims_example 0
#define TEST_reduce_min_do_not_keepdims_random 0
#define TEST_reduce_min_keepdims_example 0
#define TEST_reduce_min_keepdims_random 0
#define TEST_reduce_min_negative_axes_keepdims_example 0
#define TEST_reduce_min_negative_axes_keepdims_random 0
#define TEST_reduce_prod_default_axes_keepdims_example 0
#define TEST_reduce_prod_default_axes_keepdims_random 0
#define TEST_reduce_prod_do_not_keepdims_example 0
#define TEST_reduce_prod_do_not_keepdims_random 0
#define TEST_reduce_prod_keepdims_example 0
#define TEST_reduce_prod_keepdims_random 0
#define TEST_reduce_prod_negative_axes_keepdims_example 0
#define TEST_reduce_prod_negative_axes_keepdims_random 0
#define TEST_reduce_sum_default_axes_keepdims_example 0
#define TEST_reduce_sum_default_axes_keepdims_random 0
#define TEST_reduce_sum_do_not_keepdims_example 0
#define TEST_reduce_sum_do_not_keepdims_random 0
#define TEST_reduce_sum_keepdims_example 0
#define TEST_reduce_sum_keepdims_random 0
#define TEST_reduce_sum_negative_axes_keepdims_example 0
#define TEST_reduce_sum_negative_axes_keepdims_random 0
#define TEST_reduce_sum_square_default_axes_keepdims_example 0
#define TEST_reduce_sum_square_default_axes_keepdims_random 0
#define TEST_reduce_sum_square_do_not_keepdims_example 0
#define TEST_reduce_sum_square_do_not_keepdims_random 0
#define TEST_reduce_sum_square_keepdims_example 0
#define TEST_reduce_sum_square_keepdims_random 0
#define TEST_reduce_sum_square_negative_axes_keepdims_example 0
#define TEST_reduce_sum_square_negative_axes_keepdims_random 0
#define TEST_reflect_pad 0
#define TEST_relu 1
#define TEST_reshape_extended_dims 0
#define TEST_reshape_negative_dim 0
#define TEST_reshape_negative_extended_dims 0
#define TEST_reshape_one_dim 0
#define TEST_reshape_reduced_dims 0
#define TEST_reshape_reordered_all_dims 0
#define TEST_reshape_reordered_last_dims 0
#define TEST_reshape_zero_and_negative_dim 0
#define TEST_reshape_zero_dim 0
#define TEST_resize_downsample_scales_cubic 0
#define TEST_resize_downsample_scales_cubic_A_n0p5_exclude_outside 0
#define TEST_resize_downsample_scales_cubic_align_corners 0
#define TEST_resize_downsample_scales_linear 0
#define TEST_resize_downsample_scales_linear_align_corners 0
#define TEST_resize_downsample_scales_nearest 0
#define TEST_resize_downsample_sizes_cubic 0
#define TEST_resize_downsample_sizes_linear_pytorch_half_pixel 0
#define TEST_resize_downsample_sizes_nearest 0
#define TEST_resize_downsample_sizes_nearest_tf_half_pixel_for_nn 0
#define TEST_resize_tf_crop_and_resize 0
#define TEST_resize_upsample_scales_cubic 0
#define TEST_resize_upsample_scales_cubic_A_n0p5_exclude_outside 0
#define TEST_resize_upsample_scales_cubic_align_corners 0
#define TEST_resize_upsample_scales_cubic_asymmetric 0
#define TEST_resize_upsample_scales_linear 0
#define TEST_resize_upsample_scales_linear_align_corners 0
#define TEST_resize_upsample_scales_nearest 0
#define TEST_resize_upsample_sizes_cubic 0
#define TEST_resize_upsample_sizes_nearest 0
#define TEST_resize_upsample_sizes_nearest_ceil_half_pixel 0
#define TEST_resize_upsample_sizes_nearest_floor_align_corners 0
#define TEST_resize_upsample_sizes_nearest_round_prefer_ceil_asymmetric 0
#define TEST_reversesequence_batch 0
#define TEST_reversesequence_time 0
#define TEST_rnn_seq_length 0
#define TEST_roialign 0
#define TEST_round 0
#define TEST_scan9_sum 0
#define TEST_scan_sum 0
#define TEST_scatter_elements_with_axis 0
#define TEST_scatter_elements_with_negative_indices 0
#define TEST_scatter_elements_without_axis 0
#define TEST_scatter_with_axis 0
#define TEST_scatter_without_axis 0
#define TEST_scatternd 0
#define TEST_selu 0
#define TEST_selu_default 0
#define TEST_selu_example 0
#define TEST_shape 0
#define TEST_shape_example 0
#define TEST_shrink_hard 0
#define TEST_shrink_soft 0
#define TEST_sigmoid 0
#define TEST_sigmoid_example 0
#define TEST_sign 0
#define TEST_simple_rnn_defaults 0
#define TEST_simple_rnn_with_initial_bias 0
#define TEST_sin 0
#define TEST_sin_example 0
#define TEST_sinh 0
#define TEST_sinh_example 0
#define TEST_size 0
#define TEST_size_example 0
#define TEST_slice 0
#define TEST_slice_default_axes 0
#define TEST_slice_default_steps 0
#define TEST_slice_end_out_of_bounds 0
#define TEST_slice_neg 0
#define TEST_slice_neg_steps 0
#define TEST_slice_negative_axes 0
#define TEST_slice_start_out_of_bounds 0
#define TEST_softmax_axis_0 0
#define TEST_softmax_axis_1 0
#define TEST_softmax_axis_2 0
#define TEST_softmax_default_axis 0
#define TEST_softmax_example 0
#define TEST_softmax_large_number 0
#define TEST_softmax_negative_axis 0
#define TEST_softplus 0
#define TEST_softplus_example 0
#define TEST_softsign 0
#define TEST_softsign_example 0
#define TEST_split_equal_parts_1d 0
#define TEST_split_equal_parts_2d 0
#define TEST_split_equal_parts_default_axis 0
#define TEST_split_variable_parts_1d 0
#define TEST_split_variable_parts_2d 0
#define TEST_split_variable_parts_default_axis 0
#define TEST_sqrt 0
#define TEST_sqrt_example 0
#define TEST_squeeze 0
#define TEST_squeeze_negative_axes 0
#define TEST_strnormalizer_export_monday_casesensintive_lower 0
#define TEST_strnormalizer_export_monday_casesensintive_nochangecase 0
#define TEST_strnormalizer_export_monday_casesensintive_upper 0
#define TEST_strnormalizer_export_monday_empty_output 0
#define TEST_strnormalizer_export_monday_insensintive_upper_twodim 0
#define TEST_strnormalizer_nostopwords_nochangecase 0
#define TEST_sub 0
#define TEST_sub_bcast 0
#define TEST_sub_example 0
#define TEST_sum_example 0
#define TEST_sum_one_input 0
#define TEST_sum_two_inputs 0
#define TEST_tan 0
#define TEST_tan_example 0
#define TEST_tanh 0
#define TEST_tanh_example 0
#define TEST_tfidfvectorizer_tf_batch_onlybigrams_skip0 0
#define TEST_tfidfvectorizer_tf_batch_onlybigrams_skip5 0
#define TEST_tfidfvectorizer_tf_batch_uniandbigrams_skip5 0
#define TEST_tfidfvectorizer_tf_only_bigrams_skip0 0
#define TEST_tfidfvectorizer_tf_onlybigrams_levelempty 0
#define TEST_tfidfvectorizer_tf_onlybigrams_skip5 0
#define TEST_tfidfvectorizer_tf_uniandbigrams_skip5 0
#define TEST_thresholdedrelu 0
#define TEST_thresholdedrelu_default 0
#define TEST_thresholdedrelu_example 0
#define TEST_tile 0
#define TEST_tile_precomputed 0
#define TEST_top_k 0
#define TEST_top_k_negative_axis 0
#define TEST_top_k_smallest 0
#define TEST_transpose_all_permutations_0 0
#define TEST_transpose_all_permutations_1 0
#define TEST_transpose_all_permutations_2 0
#define TEST_transpose_all_permutations_3 0
#define TEST_transpose_all_permutations_4 0
#define TEST_transpose_all_permutations_5 0
#define TEST_transpose_default 0
#define TEST_unique_not_sorted_without_axis 0
#define TEST_unique_sorted_with_axis 0
#define TEST_unique_sorted_with_axis_3d 0
#define TEST_unique_sorted_with_negative_axis 0
#define TEST_unique_sorted_without_axis 0
#define TEST_unsqueeze_axis_0 0
#define TEST_unsqueeze_axis_1 0
#define TEST_unsqueeze_axis_2 0
#define TEST_unsqueeze_axis_3 0
#define TEST_unsqueeze_negative_axes 0
#define TEST_unsqueeze_three_axes 0
#define TEST_unsqueeze_two_axes 0
#define TEST_unsqueeze_unsorted_axes 0
#define TEST_upsample_nearest 0
#define TEST_where_example 0
#define TEST_where_long_example 0
#define TEST_xor2d 0
#define TEST_xor3d 0
#define TEST_xor4d 0
#define TEST_xor_bcast3v1d 0
#define TEST_xor_bcast3v2d 0
#define TEST_xor_bcast4v2d 0
#define TEST_xor_bcast4v3d 0
#define TEST_xor_bcast4v4d 0